bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 a-c 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 a-p 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 a-r 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 c-a 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 c-p 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 c-r 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 p-a 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 p-c 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 p-r 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 r-a 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 r-c 1
bash scripts/clip/eval_clip.sh officehome b32_ep10_officehome CLIP_ZS ViT-B/16 r-p 1